### ISSUE TITLE
你好，能一起玩么

### ISSUE THREAD

**Issue by Eattttt** [1210612175/python-#1]

**Comment by 1210612175** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yujie-chen"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 晚上10:16
收件人: "1210612175/python-"<python-@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [1210612175/python-] 你好，能一起玩么 (#1)





 
Closed #1.
